# Generated by Django 4.1.5 on 2023-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_cert"),
    ]

    operations = [
        migrations.AddField(
            model_name="cert",
            name="link",
            field=models.URLField(default="https://www.isc2.org/Certifications/CISSP"),
        ),
        migrations.AddField(
            model_name="cert",
            name="name_ar",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cert",
            name="price",
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cert",
            name="shortcut",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
